version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - todo-net

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todo-net

  db:
    image: mysql:8
    container_name: todo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "33010:3306"
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge

volumes:
  db-data:
